export default Object.freeze({
    FETCH_STASHPOINTS_REQUEST: 'FETCH_STASHPOINTS_REQUEST',
    FETCH_STASHPOINTS_FILTERED_REQUEST: 'FETCH_STASHPOINTS_FILTERED_REQUEST',
    FETCH_STASHPOINTS_SORTED_REQUEST: 'FETCH_STASHPOINTS_SORTED_REQUEST',
    SET_LOADING_REQUEST: 'SET_LOADING_REQUEST',
    API_URL: 'https://api-staging.stasher.com/v1/stashpoints',
    SORT_CAPACITY: '?sort_order=by_capacity',
    FILTER_MANCHESTER: "?city=manchester"
});